name: ci-golang-lint
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
    golang-lint:
        if: github.event_name == 'pull_request'
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version-file: 'go.mod'
                check-latest: true
            - name: golang-lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: latest
                args: --timeout=10m
